project:
  type: website
  output-dir: _site
  resources:
    - assets/**

# Post-render automation
post-render: |
  # ensure assets folder exists in _site (the built site folder)
  mkdir -p _site/assets

  # generate PDF of slides (source HTML lives in _site)
  decktape reveal _site/slides.html _site/assets/slides.pdf

  # detect GH Pages URL automatically
  REPO_URL=$(git config --get remote.origin.url)
  REPO_NAME=$(basename -s .git "$REPO_URL")
  USER_NAME=$(echo "$REPO_URL" | sed -E 's#.*[:/](.*)/.*#\1#')
  GH_URL="https://${USER_NAME}.github.io/${REPO_NAME}/slides.html"

  # generate QR code linking to the GH Pages URL
  mkdir -p _site/assets
  qrencode -o _site/assets/qrcode.png "$GH_URL"

  echo "✅ PDF and QR code generated successfully!"
